#ifndef KERNEL_HW_CONFIG_H
#define KERNEL_HW_CONFIG_H

#define IRRIGATION_PUMP_PIN      17
#define SOIL_SENSOR_ADC_INPUT    0
#define BUTTON_PIN               16

#define IRRIGATION_TRIGGER_PIN   BUTTON_PIN
#define SOIL_MOISTURE_SENSOR_PIN 26

#endif
